### PR TITLE
Closes #47: Handling issues with fetch() in browser/addon land

### LINKED ISSUE #47: SDK fetch polyfill problem
When the Firefox SDK loads code, it's loaded into an environment in which there's no `window`, no `self`, and no `global`. This throws off pretty much every `fetch` polyfill detection approach, which means `ping-centre` doesn't load properly.

For instance, in `isomorphic-fetch`, the [browser-compatible version](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-browserify.js#L5) uses `whatwg-fetch`, which in turn [assumes](https://github.com/github/fetch/blob/master/fetch.js#L458) that the global object is available as either `self` or `this`. In the case of an SDK addon, it attaches its `fetch` to the wrong object, and the polyfill doesn't work.

So, this is one way to get `fetch` into the global context in an SDK addon:

```js
require('chrome').Cu.importGlobalProperties(["fetch"]);
```

I'm working on a PR that tries the SDK approach before loading any fetch libraries. (Another approach would be to have a build step that creates an SDK-compatible ping-centre.js and a web/node compatible ping-centre.js, but I noticed you've got a Makefile in this repo, and I don't totally know how I'd do that with make.) Hopefully will have the PR out within a day or so.

### PR DESCRIPTION
**Pull request by emtwo**

### CODE REVIEW

**Comment by emtwo** [comment]
@6a68 I made some changes that should make it a lot easier to use ping centre in a Firefox addon. Let me know what you think of this (next week when you're back)

File: test/unit/ping-centre.js [hunk 1]
```diff
@@ -57,6 +57,28 @@ describe("Ping Centre Common Properties", function() {
...
+  it("uses isomorphic fetch by default", function() {
+    assert.equal(typeof platform_require, "undefined", "platform_require is not defined by default");
+    assert.equal(typeof fetch, "function");
+  });
+  it("when platform_require is defined, we don't use isomorphic fetch", function() {
+    const tmp = global.fetch;
+    global.platform_require = function() {
+      return {Cu: {
+        importGlobalProperties: function() {
+          console.log("do things");
```
Comment (pdehaan) [inline test/unit/ping-centre.js]: nit: `console.log()`

**Comment by 6a68** [comment]
refs https://github.com/mozilla/testpilot/issues/2310
